# Generated by Django 4.1.7 on 2023-02-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_brand'),
        ('store', '0002_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='Realme', on_delete=django.db.models.deletion.CASCADE, to='category.brand'),
        ),
    ]
