# Generated by Django 4.1.7 on 2023-02-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='cat_name',
        ),
    ]
